---
# TODO: More synergy between these values

sigsum_user: sigsum
sigsum_db_pw: changeme
sigsum_db_name: test

mysql_root_user: root
mysql_root_password: "{{sigsum_db_pw}}" 
mysql_database:
  - test

mysql_users:
  - user: sigsum
    password: changeme
    database_privs:
      - 'test.*:ALL'
