---
- name: Converge
  hosts: all
  become: true
  roles:
    - sigsum.tlog.sigsum_agent
  vars:
    sigsum_yubihsm_credentials:
      - { port: "12345", key_id: "500", passphrase: "allan tar kakan i 1200 baud" }
