---
- name: Enable and start litewitness
  ansible.builtin.systemd_service:
    name: litewitness
    enabled: true
    state: started

- name: Restart litewitness service
  ansible.builtin.systemd_service:
    name: litewitness
    state: restarted
