---
#
# Basic settings
#
sigsum_user: sigsum
sigsum_logname: molecule-test

# Note: must be the public key of sigsum_key listed in sigsum-secondary.yml
sigsum_secondary_pubkey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINz/oZP3Y1hpRanAU6ulH8kAs+g9pc25iHn7uNV3GOqe molecule-test

#
# Database settings
#
sigsum_db_pw: changeme
sigsum_db_name: test

mysql_users:
  - user: "{{ sigsum_user }}"
    password: "{{ sigsum_db_pw }}"
    database_privs:
      - '{{ sigsum_db_name }}.*:ALL'

# Options passed to the log server
sigsum_url_prefix: "{{ sigsum_logname }}"
sigsum_interval: 3s
sigsum_external_endpoint: "0.0.0.0:3000"
sigsum_internal_endpoint: "0.0.0.0:10000"
sigsum_trillian_rpc_server: "localhost:6962"

# When running primary and secondary on same machine, need to set different config filenames
sigsum_config_filename_primary: "config-primary.toml"
sigsum_config_filename_secondary: "config-secondary.toml"

# When running primary and secondary on same machine, need to set different tree-id filenames
sigsum_tree_id_filename_primary: "tree-id-primary"
sigsum_tree_id_filename_secondary: "tree-id-secondary"

# Primary log-server options
sigsum_secondary_url: "http://sigsum-secondary:{{ sigsum_internal_endpoint | split(':') | last }}/{{ sigsum_url_prefix }}"

# Secondary log-server options
sigsum_primary_url: "http://sigsum-primary:{{ sigsum_internal_endpoint | split(':') | last }}/{{ sigsum_url_prefix }}"

# Go tooling
sigsum_install_tools_from_sigsum_go:
  - {
     name: "sigsum-key",
     'source': 'sigsum.org/sigsum-go',
     'version': "{{ sigsum_lib_version }}",
     'handlers': [],
    }
  - {
     name: "sigsum-submit",
     'source': 'sigsum.org/sigsum-go',
     'version': "{{ sigsum_lib_version }}",
     'handlers': [],
    }
  - {
     name: "sigsum-verify",
     'source': 'sigsum.org/sigsum-go',
     'version': "{{ sigsum_lib_version }}",
     'handlers': [],
    }
