---
- name: Get Go version output
  ansible.builtin.command: go version
  changed_when: false  # not relevant for idempotence
  register: go_version

- name: Parse Go version number
  ansible.builtin.set_fact:
    go_version_num: "{{ go_version.stdout | regex_search('go([0-9.]+)') | regex_replace('go', '') }}"

- name: Require the minimum Go version
  ansible.builtin.assert:
    that:
      - "go_version_num is version('{{ golang_min_version }}', '>=')"
    fail_msg: "Go version is less than {{ golang_min_version }}"
