---
argument_specs:
  main:
    short_description: The main entry point for the myapp role.
    description:
      - Install and setup the sigsum transparency log service on the host.
      - The role requires a reachable mysql database for data storage, see the mariadb role.

    options:
      sigsum_user:
        type: "str"
        default: sigsum
        description: "The sigsum user account."

      sigsum_db_name:
        type: "str"
        default: test
        description: "The sigsum database name"

      sigsum_db_pw:
        type: "str"
        default: changeme
        description: "The sigsum database password"

      sigsum_trillian_srcdir:
        type: "str"
        default: /usr/src/trillian
        description: "The trillian source location"

      sigsum_trillian_repo:
        type: "str"
        default: https://github.com/google/trillian
        description: "The trillian source repository"

      sigsum_trillian_version:
        type: "str"
        default: v1.5.1
        description: "The trillian source repository version"

      sigsum_lib_srcdir:
        type: "str"
        default: /usr/src/sigsum-lib-go
        description: "The sigsum library source location"

      sigsum_lib_repo:
        type: "str"
        default: https://git.glasklar.is/sigsum/core/sigsum-go
        description: "The sigsum library source repository"

      sigsum_lib_version:
        type: "str"
        default: v0.1.22-22-ged74255
        description: "The sigsum library repository version"

      sigsum_log_srcdir:
        type: "str"
        default: /usr/src/sigsum-log-go
        description: "The sigsum log source location"

      sigsum_log_repo:
        type: "str"
        default: https://git.glasklar.is/sigsum/core/log-go
        description: "The sigsum log source repository"

      sigsum_log_version:
        type: "str"
        default: v0.8.0-55-g25420cb
        description: "The sigsum log repository version"

      sigsum_logname:
        type: "str"
        default: sigsum 
        description: "The sigsum log server name"

      sigsum_url_prefix:
        type: "str"
        default: ""
        description: "a prefix that precedes /<endpoint>"

      # TODO: Better description
      sigsum_role:
        type: "str"
        default: "primary"
        choices:
          - "primary"
          - "secondary"
        description: "The sigsum primary log type"

      # TODO: Improve description
      sigsum_trillian_sequencer_interval:
        type: "str"
        default: "100ms"
        description:
          - "Trillian sequencer interval."
          - "This tunes how often trillian wakes up to sequence jobs."
          - "It proceses the number of jobs specifid in the 'sigsum_trillian_batch_size' option."

      sigsum_trillian_batch_size:
        type: "int"
        default: 512
        description:
          - "Trillian batch size."
          - "Number of jobs the trillian server should process when it wakes up for sequencing."
          - "The option 'sigsum_trillian_sequencer_interval' specifies how often trillian wakes up."

      sigsum_external_endpoint:
        type: "str"
        default: "127.0.0.1:14784"
        description: "host:port specification of where sigsum-log-primary serves clients"

      sigsum_internal_endpoint:
        type: "str"
        default: "192.168.19.1:14785"
        description: "host:port specification of where sigsum-log-primary serves other log nodes"

      sigsum_trillian_rpc_server:
        type: "str"
        default: "localhost:6962"
        description: "host:port specification of where Trillian serves clients"

      sigsum_backend:
        type: "str"
        default: "backend"
        description: "the configured sigsum backend"

      sigsum_ephemeral_test_backend:
        type: "bool"
        default: false
        description: "if set, enables in-memory backend, with NO persistent storage"

      sigsum_timeout:
        type: "str"
        default: "10s"
        description: "timeout for backend requests"

      sigsum_key_file:
        type: "str"
        description: 
          - "key file path (openssh format), either unencrypted private key, or a public key (accessed via ssh-agent)"

      sigsum_key:
        type: "str"
        description:
          - "key string (openssh format), either unencrypted private key, or a public key (accessed via ssh-agent)"

      sigsum_interval:
        type: "str"
        default: "30s"
        description: "interval used to rotate the log's cosigned STH"

      sigsum_log_file:
        type: "path"
        default: "stderr"
        description: "file to write logs to"

      sigsum_log_level:
        type: "str"
        default: "info"
        choices:
          - "debug"
          - "info"
          - "warning"
          - "error"
        description: "log level"

          # Implementation detail
#       sigsum_configdir_base: '.config/sigsum'
#         type: "str"
#         requires: true
#         default: '.config/sigsum'
#         description: "configdir_base"


# # Primary
      sigsum_witnesses:
        type: "str"
        default: ""
        description: "comma-separated list of trusted witness public key files"

      sigsum_max_range:
        type: "int"
        default: 4096
        description: "maximum number of entries that can be retrived in a single request"

      sigsum_rate_limit_file:
        type: "str"
        default: ""
        description:
          - "enable rate limiting, based on given config file."
          - "For detailed documentation see U(https://git.glasklar.is/sigsum/core/log-go/-/blob/main/doc/rate-limit.md)."

      sigsum_allow_test_domain:
        type: "bool"
        default: false
        description: "allow submit tokens from test.sigsum.org"

      sigsum_secondary_url:
        type: "str"
        default: ""
        description: "secondary node endpoint for fetching latest replicated tree head"

      sigsum_secondary_pubkey_file:
        type: "str"
        description:
          - "public key file for secondary node"
          - "needs a file that has a openssh formated public key"
          - "only used when setting up a secondary for the primary"

      sigsum_secondary_pubkey:
        type: "str"
        description: 
          - "public key string for secondary node"
          - "needs a file that has a openssh formated public key"
          - "only used when setting up a secondary for the primary node"

# # TODO: Path wont be used
# sigsum_sth_file: "/var/lib/sigsum-log/sth"
# "path to file where latest published STH is being stored"

      sigsum_primary_url:
        type: "str"
        default: ""
        description: "primary node endpoint for fetching leaves (for secondary nodes)"
