name: ansible
namespace: sigsum
readme: README.md
repository: https://git.glasklar.is/sigsum/admin/ansible 
version: 0.1.0
authors:
  - Foxboron
  - ln5
tags:
  - sigsum
license_file: LICENSE
description: Roles and modules for installing and setting up a Sigsum log
dependencies:
  "community.mysql": "3.6.0"
