name: ansible
namespace: sigsum
readme: README.md
repository: https://git.glasklar.is/sigsum/admin/ansible 
version: 1.3.0
authors:
  - Foxboron
  - ln5
  - rgdd
  - elias
tags:
  - sigsum
license_file: LICENSE
description: Roles and modules for installing and setting up Sigsum transparency logs and witnesses
dependencies:
  "community.mysql": "3.12.0"
