---
- name: Setup a log with primary-secondary database replication
  hosts:
    - sigsum-primary
    - sigsum-secondary
  roles:
    - sigsum.tlog.mariadb
    - sigsum.tlog.sigsum

- name: Setup a primary log with ssh-agent
  hosts: sigsum-primary-ssh-agent
  roles:
    - role: sigsum.tlog.mariadb
    - role: sigsum.tlog.sigsum_agent
    - role: sigsum.tlog.sigsum
      sigsum_ssh_auth_sock: /run/sigsum-agent/sigsum-agent.socket
      sigsum_ssh_auth_group: sigsum-agent
