---
litewitness_basedir: /var/lib
litewitness_home: "{{ litewitness_basedir }}/{{ litewitness_user }}"
litewitness_database_file: "{{ litewitness_home }}/.local/share/litewitness/database"

# FIXME: remove both
litewitness_sigsum_agent_run: /run/sigsum-agent
litewitness_sigsum_agent_socket: /run/sigsum-agent/sigsum-agent.socket
