---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: trixie
    image: docker.io/library/debian:trixie
    dockerfile: ../Containerfile.Debian.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  - name: fedora43
    image: registry.fedoraproject.org/fedora:43
    dockerfile: ../Containerfile.Fedora.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"

provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
