---
- name: Verify
  hosts: all
  vars_files:
    - ../../../roles/litewitness/defaults/main.yml  # role defaults
    - ../../../roles/litewitness/vars/main.yml  # role defaults
    - vars/vars_for_verify.yml
  tasks:

    - name: Check litewitness systemd service
      ansible.builtin.systemd:
        name: "litewitness@{{ litewitness_user }}"
      register: litewitness_service_status

    - name: Assert that litewitness systemd service is running
      ansible.builtin.assert:
        that: litewitness_service_status.status.ActiveState == 'active'

    - name: Check litewitness listening addr
      ansible.builtin.wait_for:
        host: "{{ litewitness_listen_endpoint.split(':')[0] }}"
        port: "{{ litewitness_listen_endpoint.split(':')[1] }}"
        state: started

    - name: Backup initial database state
      ansible.builtin.shell: |
        sqlite3 {{ litewitness_database_file }} ".backup '{{ litewitness_database_file }}.BAK'"

    - name: Test add-checkpoint request
      ansible.builtin.shell: |
        cd /tmp
        cat << EOF > req
        old 0

        sigsum.org/v1/tree/4804b3df59edc03c0eee2a2aa5d85e2ea2636bb1709b1efd0a0fafdaeb6336f4
        4
        RfpVcbzFAvcKDDNbuRIi2dqE6cEyNzUzKw9PVjAob0Y=

        — sigsum.org/v1/tree/4804b3df59edc03c0eee2a2aa5d85e2ea2636bb1709b1efd0a0fafdaeb6336f4 McqIJKO1qTo09NJRw2f3wrJx2lLr8l2pAq42GGn3OfaoCQdHP4xxs7cocp9hsSGOD03MZ8BXrH9/SkMJ3VAkIYUXbwc=
        EOF

        cat req | curl -s -w '%{content_type}\n%{http_code}\n' --data-binary @- http://{{ litewitness_listen_endpoint }}/add-checkpoint > rsp
        [ "$(tail -n1 rsp)" = 200 ] || exit 1

        cat req | curl -s -w '%{content_type}\n%{http_code}\n' --data-binary @- http://{{ litewitness_listen_endpoint }}/add-checkpoint > rsp
        [ "$(tail -n1 rsp)" = 409 ] || exit 1

    - name: Test add-checkpoint request corresponding to a non-sigsum log
      ansible.builtin.shell: |
        cd /tmp
        cat << EOF > req
        old 0

        go.sum database tree
        35114470
        UWz2OMJzM22grOfOODJ9dzeNSOFHb0ERL/oqLWE6JlQ=

        — sum.golang.org Az3grmd4jdiw3WdxPYkhGehKbunc/owZ+BZG8uOYanUr9WoO631XJX4ibdWhA94imeZ8euyo9XfGvD5RHLfOfnXmjwg=
        EOF

        cat req | curl -s -w '%{content_type}\n%{http_code}\n' --data-binary @- http://{{ litewitness_listen_endpoint }}/add-checkpoint > rsp
        [ "$(tail -n1 rsp)" = 200 ] || exit 1

        cat req | curl -s -w '%{content_type}\n%{http_code}\n' --data-binary @- http://{{ litewitness_listen_endpoint }}/add-checkpoint > rsp
        [ "$(tail -n1 rsp)" = 409 ] || exit 1

    - name: Test update per-log bastions
      become_user: "{{ litewitness_user }}"
      become: true
      block:

        - name: Test add per-log bastions
          ansible.builtin.shell: |
            cd /tmp
            cat << EOF > per-log-bastions
            go.sum database tree
            b1.localhost:1337 b2.localhost:1337
            EOF

            ~/.local/bin/litewitness-configure {{ litewitness_database_file }} ~/.config/litewitness/log-keys ~/.config/litewitness/non-sigsum-log-keys per-log-bastions

            ~/go/bin/witnessctl list-logs -db {{ litewitness_database_file }} \
              | jq -e -s '.[] | select(.origin == "go.sum database tree") | .bastions | sort == ["b1.localhost:1337", "b2.localhost:1337"]'

        - name: Test add existing per-log bastions
          ansible.builtin.shell: |
            cd /tmp
            cat << EOF > per-log-bastions
            go.sum database tree
            b1.localhost:1337 b2.localhost:1337
            EOF

            ~/.local/bin/litewitness-configure {{ litewitness_database_file }} ~/.config/litewitness/log-keys ~/.config/litewitness/non-sigsum-log-keys per-log-bastions

            ~/go/bin/witnessctl list-logs -db {{ litewitness_database_file }} \
              | jq -e -s '.[] | select(.origin == "go.sum database tree") | .bastions | sort == ["b1.localhost:1337", "b2.localhost:1337"]'

        - name: Test remove per-log bastions
          ansible.builtin.shell: |
            cd /tmp
            cat << EOF > per-log-bastions
            go.sum database tree
            b1.localhost:1337
            EOF

            ~/.local/bin/litewitness-configure {{ litewitness_database_file }} ~/.config/litewitness/log-keys ~/.config/litewitness/non-sigsum-log-keys per-log-bastions

            ~/go/bin/witnessctl list-logs -db {{ litewitness_database_file }} \
              | jq -e -s '.[] | select(.origin == "go.sum database tree") | .bastions | sort == ["b1.localhost:1337"]'

    - name: Restore initial database state
      ansible.builtin.shell: |
        systemctl stop litewitness@{{ litewitness_user }}
        rm {{ litewitness_database_file }}-wal
        rm {{ litewitness_database_file }}-shm
        mv {{ litewitness_database_file }}.BAK {{ litewitness_database_file }}
        chown {{ litewitness_user }}:{{ litewitness_user }} {{ litewitness_database_file }}
        systemctl start litewitness@{{ litewitness_user }}
