FROM {{ item.image }}

ENV container podman
STOPSIGNAL SIGRTMIN+3

RUN dnf -y install systemd systemctl python3

VOLUME [ "/tmp", "/run", "/run/lock", "/sys/fs/cgroup" ]

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
  /etc/systemd/system/*.wants/* \
  /lib/systemd/system/local-fs.target.wants/* \
  /lib/systemd/system/sockets.target.wants/*udev* \
  /lib/systemd/system/sockets.target.wants/*initctl* \
  /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
  /lib/systemd/system/systemd-update-utmp*

CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target" ]
