---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable yubihsm-present-p timers
  ansible.builtin.systemd_service:
    name: "yubihsm-present-p@{{ item.name }}.timer"
    state: started
    enabled: true
  with_items: "{{ yubihsm_connector_monitored_instances }}"

- name: Restart yubihsm-connector instances
  ansible.builtin.systemd_service:
    name: "yubihsm-connector@{{ item.name }}"
    state: restarted
  with_items: "{{ yubihsm_connector_instances }}"

- name: Enable yubihsm-connector instances
  ansible.builtin.systemd_service:
    name: "yubihsm-connector@{{ item.name }}"
    enabled: true
    state: started
  with_items: "{{ yubihsm_connector_instances }}"

- name: reload udev rules
  listen: "yubihsm-connector udev refresh"
  ansible.builtin.command: udevadm control --reload-rules
  when: yubihsm_connector_manage_udev | default(true)

- name: retrigger udev for yubihsm hardware
  listen: "yubihsm-connector udev refresh"
  ansible.builtin.command: >
    udevadm trigger --subsystem-match=usb --attr-match=idVendor=1050
  when: yubihsm_connector_manage_udev | default(true)
