---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable yubihsm-present-p timers
  ansible.builtin.systemd_service:
    name: "yubihsm-present-p@{{ item.name }}.timer"
    state: started
    enabled: true
  with_items: "{{ yubihsm_connector_monitored_instances }}"

- name: Restart yubihsm-connector instances
  ansible.builtin.systemd_service:
    name: "yubihsm-connector@{{ item.name }}"
    state: restarted
  with_items: "{{ yubihsm_connector_instances }}"

- name: Enable yubihsm-connector instances
  ansible.builtin.systemd_service:
    name: "yubihsm-connector@{{ item.name }}"
    enabled: true
    state: started
  with_items: "{{ yubihsm_connector_instances }}"
