---
# The name of the witness.  Use a schema-less URL for a domain name that you
# control.  This helps avoid accidental naming collisions for witnesses.  The
# URL does not need to be network reachable.
#
# ---Example
# litewitness_name: example.org/witness
#
litewitness_name: ""

# Keyhash of the public Ed25519 witness key (hint: sigsum-key to-hash -k
# /path/to/pubkey).  This is used as a handle when accessing the private key
# via the SSH agent protocol (using sigsum-agent).
#
# ---Example
# litewitness_keygrip: 70ef4421b0ff38436855c2650988da6b03309d2105d6280fbb30dd1e635954ae
#
litewitness_keygrip: ""

# Define which logs to be witnessed and whether they have their own bastion
# host(s).  It is required to supply `vkey`.  It is optional to supply `origin`
# and `bastions`.  The default value for `origin` is the `vkey` key name.
#
# ---Example
# litewitness_logs:
#   - vkey: "sum.golang.org+033de0ae+Ac4zctda0e5eza+HJyk9SxEdh+s3Ux18htTTAD8OuAn8"
#     origin: "go.sum database tree"
#     bastions:
#       - "b1.example.org:443"
#       - "b2.example.org:443"
#
litewitness_logs: []

# Optionally discover logs to witness from a centrally managed list.  The
# expected list format is defined by <https://witness-network.org/>.
#
# ---Example
# litewitness_pull_logs:
#   - https://testing.witness-network.org/log-list.1
#
litewitness_pull_logs: []

# Schedule for the job that pulls logs from a centrally managed list, specified
# using the crontab(5) format.  By default, the job runs every 15 minutes.
#
# ---Example
# litewitness_pull_logs_schedule:
#   minute: "0"
#   hour: "*/2"
#
litewitness_pull_logs_schedule:
  minute: "*/15"

# Address to listen for witness requests.
# Note: you need to sort out HTTPS reverse proxying outside of this role.
litewitness_listen_endpoint: ""

# Toggle / and /logz endpoints
litewitness_debug_endpoints_enabled: false

# Address to listen for metrics requests, instead of exposing them on the main
# listener.
litewitness_listen_metrics: ""
