---
- name: Install requirements
  hosts: all
  gather_facts: no
  pre_tasks:
  - name: Install python3
    raw: 'apt update && apt install -y python3'
    args:
      executable: /bin/bash

  - name: Install basic dependencies
    ansible.builtin.apt:
      name:
        - sudo
        - systemd
        - sqlite3  # litewitness
      state: present

  - name: Install debug tooling
    ansible.builtin.apt:
      name:
        - less
        - vim
        - curl
        - iproute2
        - ldnsutils
        - iputils-ping
        - netcat-traditional
      state: present
