---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: bookworm
    image: docker.io/library/debian:bookworm
    dockerfile: ../Dockerfile.debian.bookworm.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /run/lock
      - /tmp

provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare_debian.yml
