---

sigsum_user: sigsum
sigsum_home: "/var/sigsum/{{ sigsum_user }}"
sigsum_db_name: test

# For sigsum_db_pw, create a '!vault' blob by running the following
# command and put the result it in a host_vars/ file. To avoid a newline
# in the value, press C-d twice.
#   ansible-vault encrypt_string --vault-id host@/etc/vault/$(hostname -s)_vault_secret
#
# WARNING: The unencrypted value will end up in a world readable file
# on the target system.
#
sigsum_db_pw: changeme

#
# The default Go module source and version can be overriden by setting "source"
# and "version".  For example, sigsum-key could be installed with this syntax:
# - { name: "sigsum-key", source: "sigsum.org/sigsum-go", version: "v0.6.1" }
#
sigsum_lib_version: "v0.6.1"  # default version for tools from sigsum-go
sigsum_tools_from_sigsum_go:
  - { name: "sigsum-key" }

sigsum_log_version: "v0.14.1"  # default version for tools from log-go
sigsum_tools_from_log_go:
  - { name: "sigsum-mktree" }
  - { name: "sigsum-log-primary" }
  - { name: "sigsum-log-secondary" }

sigsum_trillian_version: "v1.5.2"  # default version for tools from trillian
sigsum_tools_from_trillian_go:
  - { name: "createtree" }
  - { name: "trillian_log_signer" }
  - { name: "trillian_log_server" }

sigsum_trillian_sequencer_interval: 100ms
sigsum_trillian_batch_size: 100

sigsum_logname: sigsum
sigsum_url_prefix: sigsum

sigsum_role: "primary"

sigsum_external_endpoint: "127.0.0.1:14784"
sigsum_internal_endpoint: "127.0.0.1:14785"
sigsum_trillian_rpc_server: "localhost:6962"
sigsum_timeout: 10s
sigsum_key: ""
sigsum_key_file: ""
sigsum_interval: 30s
sigsum_log_file: ""
sigsum_log_level: "info"
sigsum_backend: "trillian"

# Primary
sigsum_max_range: 4096
sigsum_rate_limit_file: ""
sigsum_allow_test_domain: false
sigsum_secondary_url: ""
sigsum_secondary_pubkey: ""
sigsum_secondary_pubkey_file: ""
sigsum_witness_config: ""

# Secondary
sigsum_primary_url: ""
