---

sigsum_user: sigsum
sigsum_db_name: test

# For sigsum_db_pw, create a '!vault' blob by running the following
# command and put the result it in a host_vars/ file. To avoid a newline
# in the value, press C-d twice.
#   ansible-vault encrypt_string --vault-id host@/etc/vault/$(hostname -s)_vault_secret
#
# WARNING: The unencrypted value will end up in a world readable file
# on the target system.
#
sigsum_db_pw: changeme

# TODO: Add the ability to run multiple instances of different
# versions on a single node. Combinations of trillian and sigsum-go
# dependencies might be necessary too.

sigsum_trillian_srcdir: /usr/src/trillian
sigsum_trillian_repo: https://github.com/google/trillian
sigsum_trillian_version: v1.5.1

sigsum_lib_srcdir: /usr/src/sigsum-lib-go
sigsum_lib_repo: https://git.glasklar.is/sigsum/core/sigsum-go
sigsum_lib_version: v0.1.23

sigsum_log_srcdir: /usr/src/sigsum-log-go
sigsum_log_repo: https://git.glasklar.is/sigsum/core/log-go
sigsum_log_version: v0.9.0

sigsum_configdir_base: '.config/sigsum'

sigsum_trillian_sequencer_interval: 100ms
sigsum_trillian_batch_size: 100

sigsum_logname: sigsum
sigsum_url_prefix: sigsum

sigsum_role: "primary"

sigsum_external_endpoint: "127.0.0.1:14784"
sigsum_internal_endpoint: "192.168.19.1:14785"
sigsum_trillian_rpc_server: "localhost:6962"
sigsum_timeout: 10s
sigsum_key: ""
sigsum_key_file: ""
sigsum_interval: 30s
sigsum_log_file: ""
sigsum_log_level: "info"
sigsum_backend: "trillian"

# Primary
sigsum_witnesses: ""
sigsum_max_range: 4096
sigsum_rate_limit_file: ""
sigsum_allow_test_domain: false
sigsum_secondary_url: ""
sigsum_secondary_pubkey: ""
sigsum_secondary_pubkey_file: ""

# Internal implementation detail
# TODO: Path wont be used
sigsum_sth_file: "/var/lib/sigsum-log/sth"
sigsum_trillian_tree_id_file: "/var/lib/sigsum-log/tree-id"

# Secondary
sigsum_primary_url: ""
