---

sigsum_role: primary
sigsum_url_prefix: test

sigsum_user: sigsum
sigsum_db_name: test

# For sigsum_db_pw, create a '!vault' blob by running the following
# command and put the result it in a host_vars/ file. To avoid a newline
# in the value, press C-d twice.
#   ansible-vault encrypt_string --vault-id host@/etc/vault/$(hostname -s)_vault_secret
#
# WARNING: The unencrypted value will end up in a world readable file
# on the target system.
#
sigsum_db_pw: changeme

# TODO: Add the ability to run multiple instances of different
# versions on a single node. Combinations of trillian and sigsum-go
# dependencies might be necessary too.

sigsum_trillian_srcdir: /usr/src/trillian
sigsum_trillian_repo: https://github.com/google/trillian
sigsum_trillian_version: v1.5.0

sigsum_log_srcdir: /usr/src/sigsum-log-go
sigsum_log_repo: https://git.glasklar.is/sigsum/core/log-go
sigsum_log_version: v0.6.1

sigsum_configdir_base: '~/.config/sigsum'

# Name and HTTP endpoints for log instances.
sigsum_primary_nodes:
  - logname: test
    external_endpoint: 127.0.0.1:14784
    internal_endpoint: 192.168.19.1:14785

sigsum_secondary_nodes: []

sigsum_trillian_sequencer_interval: 100ms
sigsum_trillian_batch_size: 100
