# https://mariadb.com/kb/en/standard-replication/

# Primary https://mariadb.com/kb/en/setting-up-replication/

## Enable binary logging: https://mariadb.com/kb/en/activating-the-binary-log/
## Set server id, a unique integer >= 1
## Set bind_address https://mariadb.com/kb/en/server-system-variables/#bind_address
##
## [mariadb]
## server-id={{ trillian_db_server_id }}
## bind-address
## log_bin
## log_basename={{ trillian_db_log_basename }}
## binlog_format=mixed

## Create user for replica and grant permission to connecdt
##  CREATE USER 'replication_user'@'%' IDENTIFIED BY 'bigs3cret';
##  GRANT REPLICATION SLAVE ON *.* TO 'replication_user'@'%';

# Secondaries (replicas)
##
## [mariadb]
## server-id={{ trillian_db_server_id }}

## https://mariadb.com/kb/en/gtid/


### configuring secondaries, https://mariadb.com/kb/en/change-master-to/
# CHANGE MASTER TO
#   MASTER_HOST='master.domain.com',
#   MASTER_USER='replication_user',
#   MASTER_PASSWORD='bigs3cret',
#   MASTER_PORT=3306,
#   MASTER_CONNECT_RETRY=10,
#   MASTER_USE_GTID = current_pos;  
# START SLAVE;
# SHOW SLAVE STATUS;
