---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  ####
  # With database replication
  ###
  - name: sigsum-primary
    image: docker.io/library/debian:bookworm
    dockerfile: ../Dockerfile.debian.bookworm.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    network: internal-testnet
  - name: sigsum-secondary
    image: docker.io/library/debian:bookworm
    dockerfile: ../Dockerfile.debian.bookworm.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    network: internal-testnet
  ####
  # With key accessed using ssh-agent
  ####
  - name: sigsum-primary-ssh-agent
    image: docker.io/library/debian:bookworm
    dockerfile: ../Dockerfile.debian.bookworm.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare_debian.yml
