---
#
# Exactly one of the following private-key backends must be defined:
#
#   - Soft key
#   - YubiHSM
#
# Uncomment and fill out the details for the backend of your choise.
#
# WARNING: it is a bad idea to put soft credentials like private keys and
# passphrases in this configuration file in plaintext.  Use ansible vault.  For
# a hint of how to do get started with this, see roles/sigsum's sigsum_db_pw.
#

# Configuration of a soft key (unencrypted OpenSSH private-key format)
# sigsum_agent_soft_key: ""

# Configuration of a YubiHSM
sigsum_agent_yubihsm_key_id: "500"  # default key id for logs in core/key-mgmt
sigsum_agent_yubihsm_connector_retry: true
# yubihsm credential items consist of four required key/value pairs:
#   - port: sigsum_agent_yubihsm_port
#   - auth_id: sigsum_agent_yubihsm_auth_id
#   - passphrase: sigsum_agent_yubihsm_passphrase
#   - connector: <name>  # for yubihsm-connector@<name>.service
sigsum_yubihsm_credentials: []


# If defined, specifies the YubiHSM USB device to monitor for being
# available. Syntax: serial number as per lsusb(1) output.
# sigsum_agent_yubihsm_monitor_device: 0018952892

# If defined, email is being sent if USB device is not being present.
# sigsum_agent_yubihsm_monitor_email: sysadmin@domain
