---
# The source and version of the Go-installed sigsum-agent.
sigsum_agent_gosource: "sigsum.org/key-mgmt/cmd/sigsum-agent"
sigsum_agent_goversion: "v0.2.3"

# Users that need to sign via a sigsum-agent instance must be added to the UNIX
# group `sigsum_agent_user`.  Sign using the `sigsum_agent_socket` UNIX socket.
sigsum_agent_user: "svc-sigsum-agent"
sigsum_agent_home: "/var/lib/{{ sigsum_agent_user }}"
sigsum_agent_socket: "/run/{{ sigsum_agent_user }}/sigsum-agent.socket"

#
# Exactly one of the following private-key backends must be defined:
#
#   - Soft key
#   - YubiHSM
#
# Uncomment and fill out the details for the backend of your choise.
#
# WARNING: it is a bad idea to put soft credentials like private keys and
# passphrases in this configuration file in plaintext.  Use ansible vault.  For
# a hint of how to do get started with this, see roles/sigsum's sigsum_db_pw.
#

# Configuration of a soft key (unencrypted OpenSSH private-key format)
# sigsum_agent_soft_key: ""

# Configuration of a YubiHSM
# sigsum_agent_yubihsm_passphrase: ""  # auth password for session establishment
sigsum_agent_yubihsm_auth_id: "200"  # default auth id for logs in core/key-mgmt
sigsum_agent_yubihsm_key_id: "500"  # default key id for logs in core/key-mgmt
sigsum_agent_yubihsm_addr: "localhost"  # default yubihsm-connector value
sigsum_agent_yubihsm_port: "12345"  # default yubihsm-connector value
