---
- name: Install python3
  raw: 'apt update && apt install -y python3'
  args:
    executable: /bin/bash

- name: Enable Debian testing repo
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/testing.list
    content: "deb http://deb.debian.org/debian testing main\n"

- name: Pin required packages to testing
  ansible.builtin.copy:
    src: etc/apt/preferences.d/witness-pins
    dest: /etc/apt/preferences.d/witness-pins

- name: Install basic dependencies
  ansible.builtin.apt:
    name:
      - sudo
      - procps # kill command, needed for service reload (litebastion)
      - systemd
      - sqlite3  # litewitness
    state: present

- name: Install debug tooling
  ansible.builtin.apt:
    name:
      - less
      - vim
      - curl
      - iproute2
      - ldnsutils
      - iputils-ping
      - netcat-traditional
    state: present

- name: Configure Glasklar package archive
  ansible.builtin.apt:
    deb: http://deb.glasklarteknik.se/glasklar-archive-keyring.deb

- name: Update apt metadata cache
  ansible.builtin.apt:
    update_cache: true
