---
- name: Install basic dependencies
  ansible.builtin.dnf:
    name:
      - sudo
      - util-linux-core # kill command, needed for service reload (litebastion)
      - systemd
      - sqlite3  # litewitness
    state: present

- name: Install debug tooling
  ansible.builtin.dnf:
    name:
      - less
      - vim
      - curl
      - ldns-utils
      - iputils
      - netcat
    state: present

- name: Create dir for package trust root
  ansible.builtin.file:
    path: /etc/pki/glasklar
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install package trust root files
  ansible.builtin.copy:
    src: "etc/pki/rpm-gpg/{{item}}"
    dest: "/etc/pki/glasklar/{{ item }}"
    mode: "0555"
  loop: "{{ rpm_trustroot | default([]) }}"

- name: Add Glasklar package repo
  ansible.builtin.yum_repository:
    baseurl: https://rpm.glasklarteknik.se/
    description: Glasklar Teknik
    gpgcheck: true
    gpgkey: "{{ ['/etc/pki/glasklar/'] | product(rpm_trustroot) | map('join') }}"
    metadata_expire: 5m
    name: glasklar
    repo_gpgcheck: false
    sslverify: true

- name: Update DNF metadata cache
  ansible.builtin.dnf:
    update_cache: true
