---
- name: Add user
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    home: "{{ litewitness_home }}"
    create_home: true
    system: true
    shell: "/bin/bash"
    state: present

- name: Add user to shared sigsum-agent group
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    groups: "{{ litewitness_sigsum_agent_user }}"
    append: true

- name: Create user directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ litewitness_home }}/.local/bin"
    - "{{ litewitness_home }}/.local/share/litewitness"
    - "{{ litewitness_home }}/.config/litewitness"

- name: Add litewitness configuration (log keys)
  ansible.builtin.template:
    src: "log-keys.j2"
    dest: "{{ litewitness_home }}/.config/litewitness/log-keys"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
  register: litewitness_config_1

- name: Add litewitness configuration (non-sigsum vkey log keys)
  ansible.builtin.template:
    src: "non-sigsum-log-keys.j2"
    dest: "{{ litewitness_home }}/.config/litewitness/non-sigsum-log-keys"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
  register: litewitness_config_2

- name: Add configuration script
  ansible.builtin.copy:
    src: "litewitness-configure"
    dest: "{{ litewitness_home }}/.local/bin/litewitness-configure"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
  register: litewitness_config_3

- name: Reconfigure litewitness
  ansible.builtin.command: "~/.local/bin/litewitness-configure {{ litewitness_database_file }} {{ litewitness_home }}/.config/litewitness/log-keys {{ litewitness_home }}/.config/litewitness/non-sigsum-log-keys"
  changed_when: false  # silence ansible-lint
  become_user: "{{ litewitness_user }}"
  become: true
  when: (litewitness_config_1 is changed) or (litewitness_config_2 is changed) or (litewitness_config_3 is changed)

- name: Add start script
  ansible.builtin.template:
    src: "litewitness-start.j2"
    dest: "{{ litewitness_home }}/.local/bin/litewitness-start"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
  register: litewitness_start_script

- name: Add systemd .service file
  ansible.builtin.template:
    src: litewitness@.service.j2
    dest: "/etc/systemd/system/litewitness@.service"
    mode: "0644"
  register: litewitness_systemd_service_file

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: litewitness_systemd_service_file is changed

- name: Enable and start litewitness
  ansible.builtin.systemd:
    name: "litewitness@{{ litewitness_user }}"
    enabled: true
    state: started

- name: Restart litewitness
  ansible.builtin.systemd:
    name: "litewitness@{{ litewitness_user }}"
    state: restarted
  when: (litewitness_start_script is changed) or (litewitness_systemd_service_file is changed)
