---
- name: Install litewitness.conf
  ansible.builtin.template:
    src: etc/litewitness/litewitness.conf.j2
    dest: /etc/litewitness/litewitness.conf
  notify: Restart litewitness service

# NOTE: We're missing some functionality from sigsum.ansible.litewitness-1.7.x, namely:
# * keys are not being removed, only added

- name: Configure log origins
  ansible.builtin.command:
    cmd: witnessctl add-log -db "{{ litewitness_database_file }}" -origin "{{ item.origin | default(item.vkey | split('+') | first) }}"
  loop: "{{ litewitness_logs|default([]) }}"
  become: true
  become_user: "{{ litewitness_user }}"
  register: r
  failed_when: >
    (r.rc != 0) and
    ("Error adding log: sqlite: step: constraint failed: UNIQUE constraint failed: log.origin" not in r.stderr)
  changed_when: false

- name: Configure log keys
  ansible.builtin.command:
    cmd: witnessctl add-key -db "{{ litewitness_database_file }}" -origin "{{ item.origin | default(item.vkey | split('+') | first) }}" -key "{{ item.vkey }}"
  loop: "{{ litewitness_logs|default([]) }}"
  become: true
  become_user: "{{ litewitness_user }}"
  register: r
  failed_when: >
    (r.rc != 0) and
    ("already exists for log" not in r.stderr)
  changed_when: false

- name: Install log-lists configuration
  ansible.builtin.template:
    src: etc/litewitness/log-lists.j2
    dest: /etc/litewitness/log-lists
  notify: Pull log lists

- name: Install litewitness-pull-logs script
  ansible.builtin.copy:
    src: usr/bin/litewitness-pull-logs
    dest: /usr/bin/litewitness-pull-logs
    owner: root
    group: root
    mode: "0755"

- name: Install litewitness-pull-logs systemd service
  ansible.builtin.template:
    src: etc/systemd/system/litewitness-pull-logs.service.j2
    dest: /etc/systemd/system/litewitness-pull-logs.service
    mode: "0644"
  notify: Reload systemd

- name: Install litewitness-pull-logs systemd timer
  ansible.builtin.template:
    src: etc/systemd/system/litewitness-pull-logs.timer.j2
    dest: /etc/systemd/system/litewitness-pull-logs.timer
    mode: "0644"
  notify:
    - Reload systemd
    - Enable and start litewitness-pull-logs timer
