---
- name: Configure non-sigsum logs
  ansible.builtin.command:
    # FIXME: if item.origin is defined, use it instead of first part of vkey
    cmd: "witnessctl add-log -db {{ litewitness_database_file }} -origin {{ item.vkey | split('+') | first }}"
  loop: "{{ litewitness_logs|default([]) }}"

- name: Configure log keys
  ansible.builtin.command:
    cmd: "witnessctl add-log -db {{ litewitness_database_file }} -key {{ item.vkey }}"
  loop: "{{ litewitness_logs|default([]) }}"
