---
- ansible.builtin.include_tasks: constraints.yml
- ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"

- name: Add user to sigsum-agent group
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    groups: sigsum-agent
    append: true

- ansible.builtin.include_tasks: configure.yml
