---
- name: Add user
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    home: "{{ litewitness_home }}"
    create_home: true
    system: true
    shell: "/bin/bash"
    state: present

- name: Add user to shared sigsum-agent group
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    groups: "{{ litewitness_sigsum_agent_user }}"
    append: true

- name: Create user directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ litewitness_home }}/.local/bin"
    - "{{ litewitness_home }}/.local/share/litewitness"
    - "{{ litewitness_home }}/.config/litewitness"
