---
- name: Add user
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    home: "{{ litewitness_home }}"
    create_home: true
    system: true
    seuser: "user_u"
    shell: "/bin/bash"
    state: present

- name: Add user to shared sigsum-agent group
  ansible.builtin.user:
    name: "{{ litewitness_user }}"
    groups: "{{ litewitness_sigsum_agent_user }}"
    append: true

- name: Create user directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    setype: "{{ item.setype }}"
    owner: "{{ litewitness_user }}"
    group: "{{ litewitness_user }}"
    mode: "0755"
    state: directory
  loop:
    - path: "{{ litewitness_home }}/.local/bin"
      # TODO: would home_bin_t do?
      setype: bin_t
    - path: "{{ litewitness_home }}/.local/share"
      setype: data_home_t
    - path: "{{ litewitness_home }}/.local/share/litewitness"
      setype: data_home_t
    - path: "{{ litewitness_home }}/.config/litewitness"
      setype: config_home_t
