---
#
# Basic settings
#
sigsum_user: sigsum
sigsum_role: primary
sigsum_logname: molecule-test

sigsum_allowlist_limit: 1024
sigsum_allowlist_keys:
  - key_hash: 55e42395281d18e8fd7252b99bd993fd7d450135a5a97a329884f1f99e796442
    limit: 1024  # see host_vars/test.yml for generation of this test key
sigsum_allowlist_domains:
  - domain: example.org
    limit: 32  # dummy entry just to ensure generated config is accepted

sigsum_key: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINz/oZP3Y1hpRanAU6ulH8kAs+g9pc25iHn7uNV3GOqe molecule-test
sigsum_agent_soft_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACDc/6GT92NYaUWpwFOrpR/JALPoPaXNuYh5+7jVdxjqngAAAJDS2Q5C0tkO
  QgAAAAtzc2gtZWQyNTUxOQAAACDc/6GT92NYaUWpwFOrpR/JALPoPaXNuYh5+7jVdxjqng
  AAAECxLfg+B3N3xGF2NY5DzErqRNtKGkXphQEYTH8LV8eLw9z/oZP3Y1hpRanAU6ulH8kA
  s+g9pc25iHn7uNV3GOqeAAAADW1vbGVjdWxlLXRlc3Q=
  -----END OPENSSH PRIVATE KEY-----

#
# Database settings
#
sigsum_db_pw: changeme
sigsum_db_name: test

mysql_root_user: root
mysql_root_password: "{{ sigsum_db_pw }}"
mysql_users:
  - user: "{{ sigsum_user }}"
    password: "{{ sigsum_db_pw }}"
    database_privs:
      - '{{ sigsum_db_name }}.*:ALL'

# Options passed to the log server
sigsum_url_prefix: "{{ sigsum_logname }}"
sigsum_interval: 3s
sigsum_external_endpoint: "0.0.0.0:3000"
sigsum_internal_endpoint: "0.0.0.0:10000"
sigsum_trillian_rpc_server: "localhost:6962"

# Go tooling
sigsum_tools_from_sigsum_go:
  - { name: "sigsum-key" }  # needed by sigsum role
  - { name: "sigsum-submit" }  # needed by verify.yml
  - { name: "sigsum-verify" }  # needed by verify.yml
