---
#
# Basic settings
#
sigsum_user: sigsum
sigsum_role: secondary
sigsum_logname: molecule-test

sigsum_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACDc/6GT92NYaUWpwFOrpR/JALPoPaXNuYh5+7jVdxjqngAAAJDS2Q5C0tkO
  QgAAAAtzc2gtZWQyNTUxOQAAACDc/6GT92NYaUWpwFOrpR/JALPoPaXNuYh5+7jVdxjqng
  AAAECxLfg+B3N3xGF2NY5DzErqRNtKGkXphQEYTH8LV8eLw9z/oZP3Y1hpRanAU6ulH8kA
  s+g9pc25iHn7uNV3GOqeAAAADW1vbGVjdWxlLXRlc3Q=
  -----END OPENSSH PRIVATE KEY-----

#
# Database settings
#
sigsum_db_pw: changeme
sigsum_db_name: test

mysql_root_user: root
mysql_root_password: "{{ sigsum_db_pw }}"
mysql_users:
  - user: "{{ sigsum_user }}"
    password: "{{ sigsum_db_pw }}"
    database_privs:
      - '{{ sigsum_db_name }}.*:ALL'

# Options passed to the log server
sigsum_url_prefix: "{{ sigsum_logname }}"
sigsum_interval: 1s
sigsum_external_endpoint: "0.0.0.0:3000"
sigsum_internal_endpoint: "0.0.0.0:10000"
sigsum_trillian_rpc_server: "localhost:6962"

# Secondary log-server options
sigsum_primary_url: "http://sigsum-primary:{{ sigsum_internal_endpoint | split(':') | last }}/{{ sigsum_url_prefix }}"
