---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: bookworm
    image: docker.io/library/debian:bookworm
  - name: bookworm-backports
    image: docker.io/library/debian:bookworm  # the golang role will configure backports
  - name: trixie
    image: docker.io/library/debian:trixie

provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare_debian.yml
