---
# Log level used by all YubiHSM connector instances.
# Available: trace, debug, info, warn, error, fatal, panic.
yubihsm_connector_log_level: warn

# Specify one or more YubiHSM connector instances.  Each instance results in
#
#   /etc/yubihsm-connector-<name>.yaml
#
# being created with a corresponding systemd service instance:
#
#   yubihsm-connector@<name>.service
#
# Example:
#
#   yubihsm_connector_instances:
#     - name: hsm1
#       serial_number: 11111111
#       port: 12345
#
# name is arbitrary.
# serial_number must match the YubiHSM device.
# port must be available for listening on 127.0.0.1.
yubihsm_connector_instances: []

# Debian package source base URL.
yubihsm_connector_debian_deb_source: https://deb.debian.org/debian

# Optional Debian package override. Takes effect if there's a matching arch
# item, in which case the listed .deb package is downloaded and installed.
#
# Example:
#
#   yubihsm_connector_pkg:
#     - name: yubihsm-connector_3.0.7-1_arm64.deb
#       arch: aarch64
#       url: https://www.glasklarteknik.se/archive/pkg/yubihsm-connector_3.0.7-1_arm64.deb
#       checksum: sha256:ade548f674e4b9b795ed43b02c037e9aa8dd863b79e25b70c18870e8c396eee6
yubihsm_connector_pkg: []
