---
- name: Decide if a specific yubihsm_connector package should be installed
  ansible.builtin.set_fact:
    local_yhsmcon_pkg: "{{ yubihsm_connector_pkg |
        selectattr('arch', 'equalto', ansible_facts['architecture']) |
        first |
        default({}) }}"
  when: yubihsm_connector_pkg is defined

- ansible.builtin.include_tasks: Debian.backports.yml
  when: local_yhsmcon_pkg | default({}) == {}

- ansible.builtin.include_tasks: Debian.specific.yml
  when: local_yhsmcon_pkg | default({}) != {}
