---
- name: Download yubihsm_connector package
  ansible.builtin.get_url:
    url: "{{ local_yhsmcon_pkg.url }}"
    dest: "/usr/local/share/{{ local_yhsmcon_pkg.name }}"
    checksum: "{{ local_yhsmcon_pkg.checksum }}"

- name: Install yubihsm_connector from specific package
  ansible.builtin.apt:
    deb: "/usr/local/share/{{ local_yhsmcon_pkg.name }}"
