---
- name: Install yubihsm-connector
  ansible.builtin.dnf:
    name:
      - yubihsm-connector

- name: Enable yubihsm_connector service
  ansible.builtin.systemd_service:
    name: yubihsm_connector
    enabled: true
    state: started
