---
- name: Install yubihsm-connector
  ansible.builtin.dnf:
    name:
      - yubihsm-connector

- name: Disable yubihsm-connector service since we are using instantiated variant
  ansible.builtin.systemd_service:
    name: yubihsm-connector
    enabled: false
    state: stopped
