---
- name: Install yubihsm-connector
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"

- name: Disable yubihsm-connector service since we are using instantiated variant
  ansible.builtin.systemd_service:
    name: yubihsm-connector
    enabled: false
    state: stopped

- name: Configure yubihsm-connector instances
  ansible.builtin.template:
    src: etc/yubihsm-connector.yaml.j2
    dest: "/etc/yubihsm-connector-{{ item.name }}.yaml"
    mode: '0644'
  with_items: "{{ yubihsm_connector_instances }}"
  notify:
    - Restart yubihsm-connector instances
    - Enable yubihsm-connector instances

- name: Create yubihsm-connector systemd instantiated service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/yubihsm-connector@.service
    src: etc/systemd/system/yubihsm-connector@.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart yubihsm-connector instances
    - Enable yubihsm-connector instances
#
###
# Enable YubiHSM device monitoring
###
- ansible.builtin.include_tasks: monitor.yml
  when: sigsum_agent_yubihsm_monitor_device is defined
