---
- name: Install yubihsm-connector
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"

- name: Configure yubihsm-connector instances
  ansible.builtin.template:
    src: etc/yubihsm-connector.yaml.j2
    dest: "/etc/yubihsm-connector-{{ item.name }}.yaml"
    mode: '0644'
  with_items: "{{ yubihsm_connector_instances }}"

- name: Create yubihsm-connector systemd instantiated service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/yubihsm-connector@.service
    src: etc/systemd/system/yubihsm-connector@.service

- name: Create yubihsm-connector-manager.service file
  ansible.builtin.template:
    dest: /etc/systemd/system/yubihsm-connector-manager.service
    src: etc/systemd/system/yubihsm-connector-manager.service.j2

- name: Enable yubihsm-connector-manager service
  ansible.builtin.systemd_service:
    name: yubihsm-connector-manager
    enabled: true
    state: started
