---
- name: Install yubihsm-connector from package manager
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Install build dependencies
  ansible.builtin.apt:
    pkg:
      - make
      - libusb-1.0-0-dev

# TODO: Don't clone as root
- name: Clone yubihsm-connector source code
  ansible.builtin.git:
    repo: "{{ yubihsm_connector_source_repo }}"
    version: "{{ yubihsm_connector_source_version|default(HEAD) }}"
    dest: /usr/src/yubihsm-connector

# TODO: Don't build as root
- name: Build yubihsm-connector binary from source
  ansible.builtin.command:
    chdir: /usr/src/yubihsm-connector
    cmd: make build

- name: Install yubihsm-connectory binary over package manager version
  ansible.builtin.command:
    chdir: /usr/src/yubihsm-connector
    cmd: install ./bin/yubihsm-connector /usr/bin/
