---

- block:
  when: yubihsm_connector_monitor_email is defined
  - name: Install a mail program (Debian)
    when: ansible_facts['distribution'] == "Debian"
    ansible.builtin.apt:
      name: mailutils

  - name: Install a mail program (Fedora)
    when: ansible_facts['distribution'] == "Fedora"
    ansible.builtin.dnf:
      name: s-nail

- name: Install script verifying the presence of a YubiHSM device
  ansible.builtin.copy:
    dest: /usr/bin/yubihsm-present-p
    src: usr/bin/yubihsm-present-p
    mode: '0755'

- name: Create service verifying the presence of a YubiHSM device
  ansible.builtin.template:
    dest: /etc/systemd/system/yubihsm-present-p.service
    src: etc/systemd/system/yubihsm-present-p.service.j2
    mode: '0644'
  notify: Reload systemd

- name: Create timer for yubihsm-present-p
  ansible.builtin.copy:
    dest: /etc/systemd/system/yubihsm-present-p.timer
    src: etc/systemd/system/yubihsm-present-p.timer
    mode: '0644'
  notify: Reload systemd

- name: Enable timer for yubihsm-present-p
  ansible.builtin.systemd_service:
    name: yubihsm-present-p.timer
    state: started
    enabled: true
