---

- block:
  when: yubihsm_connector_monitor_email is defined
  - name: Install a mail program (Debian)
    when: ansible_facts['distribution'] == "Debian"
    ansible.builtin.apt:
      name: mailutils

  - name: Install a mail program (Fedora)
    when: ansible_facts['distribution'] == "Fedora"
    ansible.builtin.dnf:
      name: s-nail

- name: Install script verifying the presence of a YubiHSM device
  ansible.builtin.copy:
    dest: /usr/bin/yubihsm-present-p
    src: usr/bin/yubihsm-present-p
    mode: '0755'

- name: Create directory for yubihsm-present-p environment files
  ansible.builtin.file:
    path: /etc/yubihsm-present-p
    state: directory
    mode: '0755'

- name: Configure yubihsm-present-p environment files
  ansible.builtin.template:
    dest: "/etc/yubihsm-present-p/{{ item.name }}.conf"
    src: etc/yubihsm-present-p.conf.j2
    mode: '0644'
  loop: "{{ yubihsm_connector_monitored_instances }}"
  notify: Enable yubihsm-present-p timers

- name: Create service verifying the presence of YubiHSM devices
  ansible.builtin.copy:
    dest: /etc/systemd/system/yubihsm-present-p@.service
    src: etc/systemd/system/yubihsm-present-p@.service
    mode: '0644'
  notify: Reload systemd

- name: Create timer for yubihsm-present-p instances
  ansible.builtin.copy:
    dest: /etc/systemd/system/yubihsm-present-p@.timer
    src: etc/systemd/system/yubihsm-present-p@.timer
    mode: '0644'
  notify: Reload systemd
