---
# The sigsum project follows the Go version in Debian backports.
# https://git.glasklar.is/sigsum/project/documentation/-/blob/main/archive/2023-01-24--meeting-minutes#L37
golang_min_version: 1.22
