---

# TODO: Consider adding support for multiple instances running
# different versions of trillian and sigsum-log-go. For testing a new
# version, or for keeping an instance of an older protocol alive.

- name: Install dependencies
  apt:
    pkg:
    - golang
    - git

- name: Create {{ sigsum_user }} user for sigsum
  user:
    name: "{{ sigsum_user }}"
    password_lock: true
    home: "/var/sigsum/{{ sigsum_user }}"
    system: true

- name: Prepare Trillian source directory
  file:
    path: "{{ sigsum_trillian_srcdir }}"
    state: directory
    mode: 0755
    owner: "{{ sigsum_user }}"
    group: "{{ sigsum_user }}"

- name: Prepare git.sigsum.org/sigsum-go source directory
  file:
    path: "{{ sigsum_lib_srcdir }}"
    state: directory
    mode: 0755
    owner: "{{ sigsum_user }}"
    group: "{{ sigsum_user }}"

- name: Prepare git.sigsum.org/log-go source directory
  file:
    path: "{{ sigsum_log_srcdir }}"
    state: directory
    mode: 0755
    owner: "{{ sigsum_user }}"
    group: "{{ sigsum_user }}"

- name: Clone Trillian
  become: yes
  become_user: "{{ sigsum_user }}"
  git:
    repo: "{{ sigsum_trillian_repo }}"
    version: "{{ sigsum_trillian_version }}"
    dest: "{{ sigsum_trillian_srcdir }}"

- name: Build and install Trillian
  become: yes
  become_user: "{{ sigsum_user }}"
  command: go install ./...
  args:
    chdir: "{{ sigsum_trillian_srcdir }}"

- name: Clone git.sigsum.org/sigsum-go
  become: yes
  become_user: "{{ sigsum_user }}"
  git:
    repo: "{{ sigsum_lib_repo }}"
    version: "{{ sigsum_lib_version }}"
    dest: "{{ sigsum_lib_srcdir }}"

- name: Build and install git.sigsum.org/sigsum-go
  become: yes
  become_user: "{{ sigsum_user }}"
  command: go install ./...
  args:
    chdir: "{{ sigsum_lib_srcdir }}"

- name: Clone git.sigsum.org/log-go
  become: yes
  become_user: "{{ sigsum_user }}"
  git:
    repo: "{{ sigsum_log_repo }}"
    version: "{{ sigsum_log_version }}"
    dest: "{{ sigsum_log_srcdir }}"

- name: Build and install git.sigsum.org/log-go
  become: yes
  become_user: "{{ sigsum_user }}"
  #command: go install -ldflags="-X main.gitCommit=$(git rev-list -1 HEAD)" ./...
  command: go install ./...
  args:
    chdir: "{{ sigsum_log_srcdir }}"
  notify:
    - restart sigsum primary node
    - restart sigsum secondary node

# Try to create the database, if it sucsseeds, then we
# should run the resetdb.sh script.
- name: check if database exists
  community.mysql.mysql_db:
    name: "{{ sigsum_db_name }}"
    login_user: "{{ sigsum_user }}"
    login_password: "{{ sigsum_db_pw }}"
    state: present
  register: database_exists

- block:
  - name: Initiate db
    command: "{{ sigsum_trillian_srcdir }}/scripts/resetdb.sh --force"
    args:
      chdir: "{{ sigsum_trillian_srcdir }}"
    environment:
      MYSQL_USER: "{{ sigsum_user }}"
      MYSQL_DATABASE: "{{ sigsum_db_name }}"
      MYSQL_PASSWORD: "{{ sigsum_db_pw }}"
      MYSQL_ROOT_USER: "{{ mysql_root_user }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
  when: database_exists.changed

- name: Install sigsum-log startup script
  copy:
    src: sigsum-log-start.sh
    dest: /usr/bin/sigsum-log-start.sh
    mode: 0755

- name: Install service units
  template:
    src: "{{ item }}.service.j2"
    dest: "/lib/systemd/system/{{ item }}.service"
  with_items:
    - trillian-signer
    - trillian-server
    - sigsum-log-primary@
    - sigsum-log-secondary@
  notify: reload systemd

- name: Enable trillian service units
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - trillian-signer
    - trillian-server

- name: Prepare config directories for sigsum instance
  file:
    path: "/var/sigsum/{{sigsum_user}}/{{ sigsum_configdir_base }}/{{ sigsum_logname }}"
    state: directory
    mode: 0755
    owner: "{{ sigsum_user }}"
    group: "{{ sigsum_user }}"
  become_user: "{{ sigsum_user }}"
  become: true

- name: Install primary configuration file
  template:
    src: "config.toml.j2"
    dest: "/var/sigsum/{{sigsum_user}}/{{ sigsum_configdir_base }}/{{ sigsum_logname }}/config.toml"
  vars:
    primary: true
    external_endpoint: "{{ sigsum_external_endpoint }}"
    internal_endpoint: "{{sigsum_internal_endpoint}}"
    trillian_rpc_server: "{{sigsum_trillian_rpc_server}}"
    ephemeral_test_backend: "{{sigsum_ephemeral_test_backend}}"
    url_prefix: "{{sigsum_url_prefix}}"
    tree_id: "{{sigsum_tree_id}}"
    timeout: "{{sigsum_timeout}}"
    key: "/var/sigsum/{{sigsum_user}}/{{ sigsum_configdir_base }}/{{ sigsum_logname }}/sk"
    interval: "{{sigsum_interval}}"
    log_file: "{{sigsum_log_file}}"
    log_level: "{{sigsum_log_file}}"
    witnesses: "{{sigsum_witnesses}}"
    max_range: "{{sigsum_max_range}}"
    rate_limit_config: "{{sigsum_rate_limit_config}}"
    allow_test_domain: "{{sigsum_allow_test_domain}}"
    secondary_url: "{{sigsum_secondary_url}}"
    secondary_pubkey: "{{sigsum_secondary_pubkey}}"
    sth_path: "/var/sigsum/{{sigsum_user}}/{{ sigsum_configdir_base }}/{{ sigsum_logname }}/sth"
  become_user: "{{ sigsum_user }}"
  become: true
  when: sigsum_role == "primary"

- name: Install secondary configuration file
  template:
    src: "config.toml.j2"
    dest: "/var/sigsum/{{sigsum_user}}/{{ sigsum_configdir_base }}/{{ sigsum_logname }}/config.toml"
  vars:
    secondary: true
    external_endpoint: "{{ sigsum_external_endpoint }}"
    internal_endpoint: "{{sigsum_internal_endpoint}}"
    trillian_rpc_server: "{{sigsum_trillian_rpc_server}}"
    ephemeral_test_backend: "{{sigsum_ephemeral_test_backend}}"
    url_prefix: "{{ sigsum_url_prefix}}"
    tree_id: "{{sigsum_tree_id}}"
    timeout: "{{sigsum_timeout}}"
    key: "/var/sigsum/{{sigsum_user}}/{{ sigsum_configdir_base }}/{{ sigsum_logname }}/sk"
    interval: "{{sigsum_interval}}"
    log_file: "{{sigsum_log_file}}"
    log_level: "{{sigsum_log_file}}"
    primary_url: "{{sigsum_primary_url}}"
    primary_pubkey: "{{sigsum_primary_pubkey}}"
    test-mode: "{{sigsum_test_mode}}"
  become_user: "{{ sigsum_user }}"
  become: true
  when: sigsum_role == "secondary"


- name: Enable sigsum primary service units
  systemd:
    name: "sigsum-log-primary@{{ sigsum_logname }}"
    enabled: true
    state: started
  when: sigsum_role == "primary"

- name: Enable sigsum secondary service units
  systemd:
    name: "sigsum-log-secondary@{{ sigsum_logname }}"
    enabled: true
    state: started
  when: sigsum_role == "secondary"
