---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: bookworm
    image: docker.io/library/debian:bookworm
    dockerfile: ../Dockerfile.debian.bookworm.j2
    privileged: true
    cgroupns_mode: private
    override_command: false
    volume_mounts:
       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"

provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare_debian.yml

# The below is intentionally configured to facilitate use of:
# - molecule converge
# - molecule test
# - molecule destroy
#
scenario:
  name: litebastion
  converge_sequence:
    - prepare
    - create
    - converge
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    # Basic tests
    - verify
    # Test configuration updates
    - side_effect tests/update-backend-do.yml
    - converge
    - verify tests/update-backend-ok.yml
    # Done
    - destroy
  destroy_sequence:
    - destroy
