---
- name: Verify
  hosts: all
  tasks:
    - name: Assert litebastion service is started
      ansible.builtin.systemd_service:
        name: "litebastion@{{ litebastion_user }}"
        state: started

    - name: Assert litebastion port is open
      ansible.builtin.wait_for:
        host: "{{ litebastion_testonly_addr }}"
        port: "{{ litebastion_testonly_port }}"
        state: started
