---
- name: Generate primary key
  command: "{{ sigsum_home }}/go/bin/sigsum-key gen -o {{ sigsum_key_file }}"
  become_user: "{{ sigsum_user }}"
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart trillian
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - trillian-signer
    - trillian-server

- name: restart sigsum primary node
  systemd:
    name: "sigsum-log-primary@{{ sigsum_logname }}"
    state: restarted

- name: restart sigsum secondary node
  systemd:
    name: "sigsum-log-secondary@{{ sigsum_logname }}"
    state: restarted
